Feature/comment 데이터구조 변경 후 pull
PLMOW/Pinterest-BE pull request #12
Opened 2023-03-04 14:51 UTC by zmtlzmtl

Feature/comment 데이터구조 변경 후 pull

2023-03-04 15:18 UTC, zmtlzmtl commented on src/repositories/comment.repository.js
> +  createComment = async ({ pinId, content }) => {
userId 랜덤으로 추가

2023-03-04 15:20 UTC, zmtlzmtl commented on src/services/comment.service.js
> +  addComment = async ({ pinId, content }) => {
userId 랜덤넣기

2023-03-04 15:21 UTC, zmtlzmtl reviewed
굳굳 30개 잘봤습니다

2023-03-05 11:42 UTC, zmtlzmtl reviewed
userId 완료

2023-03-06 01:21 UTC, minenam commented on src/controllers/comment.controller.js
> +    console.log(userId, req.params, content);
console.log 삭제

2023-03-06 01:23 UTC, minenam commented on src/services/comment.service.js
> +    const existComment = await this.pinRepository.findByPinId({ pinId });
existComment 변경해야 됨

2023-03-06 01:25 UTC, minenam commented on src/services/comment.service.js
> +    if (Comment.userId !== userId) {
현재 개발 범위에서는 빼도 될 듯?

2023-03-06 01:29 UTC, minenam commented on src/repositories/comment.repository.js
> +  findByPinId = async ({ pinId }) => {
왜 중복이죠?

2023-03-06 01:30 UTC, minenam requested changes
코드 리뷰 확인부탁드립니다!

2023-03-06 04:59 UTC, minenam commented on src/services/comment.service.js
> +    const existpin = await this.pinRepository.findByPinId({ pinId });
대문자! existPin 아닌가욥

2023-03-06 05:00 UTC, minenam commented on src/services/comment.service.js
> +    const existpin = await this.pinRepository.findByPinId({ pinId });
existPin 변수 스타일 확인 부탁드려요

2023-03-06 05:02 UTC, minenam requested changes
camelCase 로 통일해주세요!

2023-03-06 05:02 UTC, minenam commented on db/migrations/20230221070000-create-saves.js
> +  /**
save 는 별도의 브랜치로 만들어주셔야 할 듯 합니다! 머지하고 PR 날려주세요.

2023-03-06 05:07 UTC, zmtlzmtl commented on src/services/comment.service.js
> +    const existpin = await this.pinRepository.findByPinId({ pinId });
확인입니다!

2023-03-06 05:19 UTC, minenam approved these changes
수고하셨습니다!

2023-03-06 05:19 UTC, merged