Feature/save
PLMOW/Pinterest-BE pull request #25
Opened 2023-03-06 09:14 UTC by zmtlzmtl

2023-03-06 09:22 UTC, minenam commented on src/services/save.service.js
> +    logger.info('SaveService.getAllPin');
저장된 핀이 없는 경우 에러가 아니라 빈 []를 반환해줘야 하지 않을까요? 핀이 없는게 비정상적인 동작은 아닙니다!

2023-03-06 09:24 UTC, minenam requested changes
질문 하나 확인 부탁드립니다!

2023-03-06 09:50 UTC, zmtlzmtl commented on src/services/save.service.js
> +    logger.info('SaveService.getAllPin');
오호 그말이 맞습니다~! 수정 드가겠습니다~~

2023-03-06 13:59 UTC, zmtlzmtl commented on src/services/save.service.js
> +    logger.info('SaveService.getAllPin');
에러가 필요가 없는것같아서 지우고, 빈배열이 반환되는것 확인했습니다!

2023-03-07 08:17 UTC, minenam approved these changes
확인 완료

2023-03-07 08:17 UTC, merged